services:
  app:
    build:
      context: ./express-app
    image: derealthink/express-app:local
    ports:
      - "3000:3000"
    container_name: express-app

  watchtower:
    image: nickfedor/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    depends_on:
      - app
